os: linux
dist: bionic
language: node_js
cache: yarn
node_js:
  - lts/*

install:
  - echo "${SFTP_HOST} ${KNOWN_HOST_SSHED} ${KNOWN_HOST_KEY}" >> $HOME/.ssh/known_hosts
  - yarn install

script:
  - yarn dist

deploy:
  skip_cleanup: true
  provider: script
  script: sh bin/deploy.sh $SFTP_USER $SFTP_HOST
